In [3]:
import numpy as np

In [4]:
lista = [1,2,3]
array = np.array(lista)

In [5]:
array

array([1, 2, 3])

In [6]:
array[0]

1

In [7]:
np.arange(0,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [8]:
np.arange(5,30)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29])

In [9]:
np.arange(5,30,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [10]:
np.zeros(shape=(10,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [11]:
np.ones(shape = (5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
aleatorios = np.random.randint(0,100,50)

In [13]:
aleatorios

array([27, 95, 38, 10, 37, 48, 81, 41, 81,  3, 64,  3, 81, 98, 56, 57, 80,
       88, 10, 54,  0,  1, 33, 75, 24, 89, 40,  6, 83, 89,  2, 62, 31, 54,
       47, 92, 46, 92, 85, 51, 17, 69, 60, 79, 92,  6, 60, 95, 82,  2])

In [14]:
aleatorios.argmax()

13

In [15]:
aleatorios.max()

98

In [16]:
aleatorios.argmin()

20

In [17]:
aleatorios.min()

0

In [18]:
aleatorios.shape

(50,)

In [19]:
aleatorios = aleatorios.reshape(10,5)

In [20]:
aleatorios

array([[27, 95, 38, 10, 37],
       [48, 81, 41, 81,  3],
       [64,  3, 81, 98, 56],
       [57, 80, 88, 10, 54],
       [ 0,  1, 33, 75, 24],
       [89, 40,  6, 83, 89],
       [ 2, 62, 31, 54, 47],
       [92, 46, 92, 85, 51],
       [17, 69, 60, 79, 92],
       [ 6, 60, 95, 82,  2]])

In [21]:
aleatorios[0,0]

27

In [22]:
aleatorios[1,1]

81